Global:
  device: gpu
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/manwen/scc3/
  eval_epoch_step: [0, 1]
  eval_batch_step: [0, 1000]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  use_tensorboard: false
  infer_img:
  character_dict_path: &character_dict_path ../tools/utils/mw_dict.txt
  max_text_length: &max_text_length 25
  use_space_char: &use_space_char False
  save_res_path:
  use_amp: True

Optimizer:
  name: AdamW
  lr: 0.0001
  weight_decay: 0.05
  filter_bias_and_bn: True

LRScheduler:
  name: OneCycleLR
  warmup_epoch: 1.5
  cycle_momentum: False

Architecture:
  model_type: rec
  algorithm: SCC3
  Transform:
  Encoder:
    name: SCC3
    img_size: [ 32, 128 ]
    out_char_num: 32
    out_channels: 192
    patch_merging: 'Conv'
    embed_dim: [ 96, 192, 256 ]
    depth: [ 3, 6, 6 ] #L1 L2 L3
    num_heads: [ 3, 6, 8 ]
    mixer: [ 'DPB','DPB','DPB','DPB','DPB','DPB','DPB','DPB',
             'DPB','DPB','DPB','DPB','DPB','DPB','DPB' ]
    local_mixer: [ 3, 5, 7]
    last_stage: True
    prenorm: True

  Decoder:
    name: CTCDecoder

Loss:
  name: CTCLoss
  zero_infinity: True

PostProcess:
  name: CTCLabelDecode
  character_dict_path: *character_dict_path
  use_space_char: *use_space_char

Metric:
  name: RecMetric
  main_indicator: acc
  is_filter: True


Train:
  dataset:
    name: LMDBDataSet
    data_dir: ../datasets/mw14850_lmdb/train/
    transforms:
      - DecodeImagePIL: # load image
          img_mode: RGB
      - PARSeqAugPIL:
      - CTCLabelEncode: # Class handling label
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - RecTVResize:
          image_shape: [32, 128]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 32
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ../datasets/mw14850_lmdb/val/
    transforms:
      - DecodeImagePIL: # load image
          img_mode: RGB
      - CTCLabelEncode: # Class handling label
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - RecTVResize:
          image_shape: [32, 128]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 32
    num_workers: 2
